### PR TITLE
fix dependencies

### PR DESCRIPTION
**Pull request by linki**
hey,

while following the instructions on the [README.md](https://github.com/zalando-techmonkeys/chimp#install) i encountered the following error while running `godep restore`:

```
godep: Dep (github.com/gin-gonic/gin) restored, but was unable to load it with error:
	Package (github.com/mattn/go-isatty) not found
godep: Dep (github.com/mattn/go-colorable) restored, but was unable to load it with error:
...
```

looks like a couple of dependencies aren't vendored and checked in. the following `go get`s get us going again: 

```
go get github.com/mattn/go-isatty
go get golang.org/x/sys/unix
```

furthermore, I noticed numerous vendored libraries that doesn't seem to be used.

pr is split up into two commits:
* https://github.com/linki/chimp/commit/7788279a7278079dad654603274f250d792c26af adds missing dependencies
* https://github.com/linki/chimp/commit/7b730c5f5235f5de5fbc922ebdec135e8a37b614 removes unused dependencies

at least this let's me compile on my machine. i have no idea why [travis](https://travis-ci.org/zalando-techmonkeys/chimp) doesn't complain :flushed: feel free to shout at me if i'm missing something here.

disclaimer: i haven't used `gopdep` much before as well as don't know what `chimp` does, so i can't tell if this messes anything up.

### CODE REVIEW

**Comment by linki** [comment]
https://github.com/zalando-techmonkeys/chimp/pull/37 seems to fix it for me. feel free to close this one.

**Comment by Raffo** [comment]
Out of curiosity: which go version do you have?

**Comment by linki** [comment]
doesn't work for me with `1.5` nor `1.6`.

**Comment by Raffo** [comment]
Interesting and happy that #37 fixes it.

**Comment by linki** [comment]
closing as https://github.com/zalando-techmonkeys/chimp/pull/37 fixes the problem.

if you happen to want to reproduce this issue, try building the following dockerfile:

```dockerfile
FROM golang:1.5

ENV GOPATH=/go
RUN go get github.com/tools/godep

RUN mkdir -p /go/src/github.com/zalando-techmonkeys/chimp
WORKDIR /go/src/github.com/zalando-techmonkeys/chimp
RUN git clone https://github.com/zalando-techmonkeys/chimp.git .
# checkout master's tip as of today
RUN git checkout ab9cac3

RUN godep restore
RUN godep go install ./...
```

**Comment by Raffo** [comment]
Thanks! :+1:

**Pull request closed without merging**
